# Etapa de construcción y test
FROM maven:3.9.4-eclipse-temurin-21 AS test
WORKDIR /app

COPY pom.xml .
COPY src ./src

# Ejecutar tests con el perfil de test
RUN mvn clean test -Dspring.profiles.active=test
